version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-dependencies:
        patterns:
          - "*"
    labels:
      - automerge
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - automerge
  # - package-ecosystem: "julia"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   groups:
  #     all-julia-packages:
  #       patterns:
  #         - "*"
