jupyter_book_task:
  auto_cancellation: true
  container:
    image: ghcr.io/sosiristseng/docker-juliabook:1.7.3.4
    cpu: 2
    memory: 8G
    use_in_memory_disk: true
  pip_script: pip install -r requirements.txt
  julia_cache:
    folder: ~/.julia
    fingerprint_script:
      - cat Project.toml
      - cat Manifest.toml
    populate_script: julia --threads=auto --project=@. --color=yes -e 'import Pkg; Pkg.instantiate()'
  install_script: julia --threads=auto --project=@. --color=yes build.jl
  build_script: jupyter-book build docs --warningiserror --keep-going -v

  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
