jupyter_book_task:
  execution_lock: $CIRRUS_BRANCH
  env:
    JOBS: 1
    TIMEOUT: 600
    # GH_TOKEN: ENCRYPTED[a83a3d33c85c1d0439cbfdb99f81551f87b7bfc3de072a36822d8019ef5f7d5a4aa6c7f47c975db2afa3a3c60f24384d]
  auto_cancellation: true
  container:
    dockerfile: .github/Dockerfile
    cpu: 1
    memory: 4G
    greedy: true
  notebook_script: >
    parallel --joblog /tmp/log -j${JOBS}
    jupyter nbconvert --to notebook
    --ExecutePreprocessor.timeout=${TIMEOUT}
    --ExecutePreprocessor.kernel_name="julia-$(julia -e 'print(VERSION.major, ".", VERSION.minor)')"
    --execute --inplace
    {} ::: docs/*.ipynb
  execution_results_script: cat /tmp/log
  build_script: |
    jupyter-book build docs/ --keep-going
  ## Requires a repo scope access GitHub PAT encrypted to `GH_TOKEN` to push to its GitHub repo
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ]]; then
  #     git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
  #     ghp-import -n -p -f docs/_build/html
  #   fi
