name: CI with dynamic parallel matrix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHE_NUM: '1'
  NBCACHE: '.cache'

permissions:
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      hash: ${{ steps.hash.outputs.id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get docker image hash
        id: hash
        run: echo "id=${{ hashFiles('Project.toml', 'Manifest.toml', 'Startup/**', '.github/Dockerfile') }}" >> "$GITHUB_OUTPUT"
      - name: Build and cache Docker container
        uses: docker/build-push-action@v7
        env:
          IMG: ghcr.io/${{ github.repository }}:${{ steps.hash.outputs.id }}
        with:
          context: .
          file: '.github/Dockerfile'
          tags: ${{ env.IMG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List notebooks as a JSON array
        id: set-matrix
        working-directory: docs
        run: echo "matrix=$(python -c 'import glob, json; print(json.dumps(glob.glob("**/*.ipynb", root_dir="docs", recursive=True) + glob.glob("**/*.jl", root_dir="docs", recursive=True)))')" >> "$GITHUB_OUTPUT"

  execute:
    needs: setup
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        notebook: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ needs.setup.outputs.hash }}
      NB: docs/${{ matrix.notebook }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache notebook
        uses: actions/cache@v6
        id: nb-cache
        with:
          path: ${{ env.NBCACHE }}
          key: notebook-${{ needs.setup.outputs.hash }}-${{ hashFiles(env.NB) }}
      - name: Execute Notebook
        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
        run: >
          docker run -w /tmp -v ${{ github.workspace }}:/tmp
          -e NB=${{ env.NB }}
          -e NBCACHE=${{ env.NBCACHE }}
          ${{ env.IMAGE }}
          julia --project=@. .github/ci.jl
      - name: Convert artifact Name
        id: art
        run: |
          sudo chown -R $USER ${{ env.NBCACHE }}
          echo "name=$(echo ${{ env.NB }} | sed 's/\//-/g')" >> "$GITHUB_OUTPUT"
      - name: Upload Notebook
        uses: actions/upload-artifact@v7
        with:
          name: notebook-${{ steps.art.outputs.name }}-${{ needs.setup.outputs.hash }}-${{ hashFiles(env.NB) }}
          path: ${{ env.NBCACHE }}
          include-hidden-files: true

  render:
    needs: execute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Download notebooks
        uses: actions/download-artifact@v8
        with:
          path: ${{ env.NBCACHE }}/
          pattern: notebook-*
          merge-multiple: true
      - name: Copy back built notebooks
        run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
      - name: Build website
        env:
          BASE_URL: /${{ github.event.repository.name }}
        working-directory: docs
        run: |
          npm install -g "jupyter-book"
          jupyter-book build --html
      - name: Upload pages artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs/_build/html'

  # CI conclusion for GitHub status check
  CI:
    needs: render
    if: always()
    runs-on: ubuntu-slim
    steps:
      - run: |
          if [[ ${{ needs.render.result }} == "success" ]]; then
            echo "Tests passed"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi

  # Deployment job
  deploy:
    name: Deploy to GitHub pages
    needs: render
    if: ${{ github.ref == 'refs/heads/main' }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
